### ISSUE TITLE
helm wikipedia broken needs to be repared

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm-wikipedia#1]
Hello @alphapapa IIRC you are the author of this code.
It is now broken due to new Wikipedia API probably, so I moved it out of Helm to maintain it as a helm module, could you have a look if you have time?
There is no header, no provide etc... for now.

Thanks.

**Comment by alphapapa** [comment]
Hi Thierry,

I think I contributed a patch, but I'm not the original author.  But sure, I will see what I can do.  :)  Thanks.

**Comment by alphapapa** [comment]
@thierryvolpiatto Ok, I fixed summary retrieval, tidied up the headers, and added a test file.  I don't seem to have permission to push to this repo, even though I'm a member of the emacs-helm org, so I pushed to a fork: https://github.com/alphapapa/helm-wikipedia

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Ok, I fixed summary retrieval, tidied up the headers, and added a test
> file.

Thanks, still not working for me after a quick test, I will try again
later when I have more time.

> I don't seem to have permission to push to this repo, even though I'm
> a member of the emacs-helm org, so I pushed to a fork:
> https://github.com/alphapapa/helm-wikipedia

You should have now permission to write on this repo, let me know if you
still have problems.

-- 
Thierry

**Comment by alphapapa** [comment]
> Thanks, still not working for me after a quick test, I will try again later when I have more time.

The latest commit should fix that, I think.  The issue was that, if a search suggestion required a redirect to reach the actual page, redirects weren't enabled, so no summary was retrieved.  e.g. `Emacs` worked, but `Emacs Lisp Package Archive` required a redirect.  Now it follows the redirect.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     Thanks, still not working for me after a quick test, I will try again later when I have more time.
>    
> The latest commit should fix that, I think. The issue was that, if a search suggestion required a redirect to reach the actual page, redirects weren't
> enabled, so no summary was retrieved. e.g. Emacs worked, but Emacs Lisp Package Archive required a redirect. Now it follows the redirect.

Thanks, but the PA is still not working, I made simplifications and fix
this issue in last PR, have a look (feel free to fix headers and else
once merged).

-- 
Thierry
